export const QR_LIST_REQUEST = 'QR_LIST_REQUEST';
export const QR_LIST_SUCCESS = 'QR_LIST_SUCCESS';
export const QR_LIST_FAIL = 'QR_LIST_FAIL';

// export const QR_DETAILS_REQUEST = 'QR_DETAILS_REQUEST';
// export const QR_DETAILS_SUCCESS = 'QR_DETAILS_SUCCESS';
// export const QR_DETAILS_FAIL = 'QR_DETAILS_FAIL';

export const QR_DELETE_REQUEST = 'QR_DELETE_REQUEST';
export const QR_DELETE_SUCCESS = 'QR_DELETE_SUCCESS';
export const QR_DELETE_FAIL = 'QR_DELETE_FAIL';

export const QR_CREATE_REQUEST = 'QR_CREATE_REQUEST';
export const QR_CREATE_SUCCESS = 'QR_CREATE_SUCCESS';
export const QR_CREATE_FAIL = 'QR_CREATE_FAIL';
export const QR_CREATE_RESET = 'QR_CREATE_RESET';

export const QR_UPDATE_REQUEST = 'QR_UPDATE_REQUEST';
export const QR_UPDATE_SUCCESS = 'QR_UPDATE_SUCCESS';
export const QR_UPDATE_FAIL = 'QR_UPDATE_FAIL';
export const QR_UPDATE_RESET = 'QR_UPDATE_RESET';

export const GITE_LIST_REQUEST = 'GITE_LIST_REQUEST';
export const GITE_LIST_SUCCESS = 'GITE_LIST_SUCCESS';
export const GITE_LIST_FAIL = 'GITE_LIST_FAIL';

export const GITE_DETAILS_REQUEST = 'GITE_DETAILS_REQUEST';
export const GITE_DETAILS_SUCCESS = 'GITE_DETAILS_SUCCESS';
export const GITE_DETAILS_FAIL = 'GITE_DETAILS_FAIL';

export const GITE_DELETE_REQUEST = 'GITE_DELETE_REQUEST';
export const GITE_DELETE_SUCCESS = 'GITE_DELETE_SUCCESS';
export const GITE_DELETE_FAIL = 'GITE_DELETE_FAIL';

export const GITE_CREATE_REQUEST = 'GITE_CREATE_REQUEST';
export const GITE_CREATE_SUCCESS = 'GITE_CREATE_SUCCESS';
export const GITE_CREATE_FAIL = 'GITE_CREATE_FAIL';
export const GITE_CREATE_RESET = 'GITE_CREATE_RESET';

export const GITE_UPDATE_REQUEST = 'GITE_UPDATE_REQUEST';
export const GITE_UPDATE_SUCCESS = 'GITE_UPDATE_SUCCESS';
export const GITE_UPDATE_FAIL = 'GITE_UPDATE_FAIL';
export const GITE_UPDATE_RESET = 'GITE_UPDATE_RESET';
